// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"10","screenWidth":"540","screenHeight":"960","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"true","ピクチャ番号の変数番号":"0","ポインタX座標の変数番号":"0","ポインタY座標の変数番号":"0","タッチ操作抑制":"false","タッチ操作抑制スイッチ":"0","戦闘中常にコモン実行":"false","並列処理として実行":"false","無効スイッチ":"0"}},
{"name":"LL_VariableWindowMV","status":true,"description":"変数を画面にウィンドウで表示します。","parameters":{}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{"itemIconSwitchId":"0","lineSpacingVariableId":"0","frameWindowSkin":"","frameWindowPadding":"18","padCharacter":"0","prefixText":""}},
{"name":"HIME_PreTitleEvents","status":true,"description":"Build your own sequence of events that should occur before\r\nthe title screen begins","parameters":{"Pre-Title Map ID":"1","Use As Title":"true"}},
{"name":"CrSaveTimeValue","status":true,"description":"セーブ時刻を記録する＋現在時刻の取得\n＋オートセーブコマンド＋セーブ時に変数を操作","parameters":{"STSwitch":"8","SaveTime":"20","Looks":"2","STYear":"0","STMonth":"21","STDate":"22","STHour":"23","STMinutes":"24","SaveSound":"1","SaveSE":"Save","STVvalue":"2","STsetValue":"0"}},
{"name":"EaseEventLoad","status":true,"description":"イベント処理軽量化","parameters":{}}
];
